version: '3'
services:
  server:
    build:
      context: ./server/
    command: npm start
    volumes:
      - ./server/:/usr/app
      - /usr/app/node_modules
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - server
    ports:
      - "3000:3000"
